name: AdHoc
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Fetch TShock
      run: |
        $r = curl -UseBasicParsing -H @{'Accept' = 'application/vnd.github.v3+json'} https://api.github.com/repos/Pryaxis/TShock/releases/latest
        $parsed = $r.content |ConvertFrom-Json
        Invoke-WebRequest $parsed.assets.browser_download_url -outfile tshock.zip
      shell: powershell
    - name: Decompress
      run: 7z.exe e tshock.zip -oEssentialsPlus\References "ServerPlugins/TShockAPI.dll" "Newtonsoft.Json.dll" "Mono.Data.Sqlite.dll" "MySql.Data.dll" "TerrariaServer.exe" "OTAPI.dll" -r
      shell: cmd
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: msbuild EssentialsPlus.sln /p:Configuration=Release
    - name: Create Artifact
      uses: actions/upload-artifact@master
      with:
        name: Essentials+
        path: EssentialsPlus\bin\Release\EssentialsPlus.dll
